In [16]:
import random
from numpy import array, zeros, diag, diagflat, dot, tril, triu
import numpy as np


def vytvor_ctvercovou_matici(n):
    return np.array([[random.randint(-20, 20) for i in range(n)] for j in range(n)])

def vytvor_vektor(n):
    return np.array([random.randint(-20, 20) for i in range(n)])

def gaussova_prima_metoda(matice, vektor):
    return list(np.linalg.solve(matice, vektor))

def jacobiho_iteracni_metoda(matice, vektor, opakovani=10, x=None):
    if not x:
        x = zeros(len(matice[0]))
    D = diag(matice)
    L = tril(matice, k = -1)
    U = triu(matice, k = 1 )
    for i in range(opakovani):
        x = (vektor - np.matmul((L + U),x))/D
    return list(x)


print(vytvor_ctvercovou_matici(2))
print(vytvor_ctvercovou_matici(3))
print(vytvor_ctvercovou_matici(4))
print(vytvor_vektor(3))
#iterani metoda

print(gaussova_prima_metoda([[2, 1],[5, 7]], [11,13]))
jacobiho_iteracni_metoda([[2, 1],[5, 7]], [11,13])

[[-12  20]
 [ 17  -8]]
[[ -3  19  20]
 [  2  -6   2]
 [-13   6 -19]]
[[  8  -2  11  -9]
 [  5 -10 -17 -16]
 [ 14 -17  18 -11]
 [-14   3  -2  16]]
[ 14  18 -10]
[7.11111111111111, -3.2222222222222214]


[7.069792348426251, -3.2034996578806454]